const GENRE_ES: Record<string, string> = {
  "Fiction": "Ficción",
  "Non-Fiction": "No ficción",
  "Science": "Ciencia",
  "Social Science": "Ciencias Sociales",
  "History": "Historia",
  "Chronology, Historical": "Historia",
  "Biography & Autobiography": "Biografía",
  "Philosophy": "Filosofía",
  "Psychology": "Psicología",
  "Religion": "Religión",
  "Poetry": "Poesía",
  "Drama": "Teatro",
  "Art": "Arte",
  "Music": "Música",
  "Cooking": "Cocina",
  "Education": "Educación",
  "Business & Economics": "Negocios",
  "Computers": "Computación",
  "Technology & Engineering": "Tecnología",
  "Medical": "Medicina",
  "Law": "Derecho",
  "Political Science": "Política",
  "Mathematics": "Matemáticas",
  "Nature": "Naturaleza",
  "Travel": "Viajes",
  "Sports & Recreation": "Deportes",
  "Juvenile Fiction": "Infantil",
  "Juvenile Nonfiction": "Juvenil",
  "Young Adult Fiction": "Juvenil",
  "Comics & Graphic Novels": "Cómics",
  "Self-Help": "Autoayuda",
  "Body, Mind & Spirit": "Espiritualidad",
  "Family & Relationships": "Familia",
  "Health & Fitness": "Salud",
  "Humor": "Humor",
  "Language Arts & Disciplines": "Lenguaje",
  "Literary Criticism": "Crítica Literaria",
  "Latin America": "Latinoamérica",
  "True Crime": "Crimen Real",
  "Transportation": "Transporte",
};

export function translateGenre(genre: string): string {
  return GENRE_ES[genre] ?? genre;
}

/** Categorías en español para selector manual */
export const CATEGORY_OPTIONS = [
  "Ficción",
  "No ficción",
  "Ciencia",
  "Ciencias Sociales",
  "Historia",
  "Biografía",
  "Filosofía",
  "Psicología",
  "Religión",
  "Poesía",
  "Teatro",
  "Arte",
  "Música",
  "Cocina",
  "Educación",
  "Negocios",
  "Computación",
  "Tecnología",
  "Medicina",
  "Derecho",
  "Política",
  "Matemáticas",
  "Naturaleza",
  "Viajes",
  "Deportes",
  "Infantil",
  "Juvenil",
  "Cómics",
  "Autoayuda",
  "Espiritualidad",
  "Familia",
  "Salud",
  "Humor",
  "Novela",
  "Cuentos",
  "Ensayo",
] as const;

/** Agrupación de categorías para el sidebar */
export const CATEGORY_GROUPS: { label: string; genres: string[] }[] = [
  {
    label: "Literatura",
    genres: ["Ficción", "No ficción", "Novela", "Cuentos", "Poesía", "Teatro", "Ensayo", "Humor", "Cómics", "Crítica Literaria"],
  },
  {
    label: "Desarrollo personal",
    genres: ["Autoayuda", "Espiritualidad", "Psicología", "Filosofía", "Salud", "Familia"],
  },
  {
    label: "Ciencias y tecnología",
    genres: ["Ciencia", "Ciencias Sociales", "Matemáticas", "Computación", "Tecnología", "Medicina", "Naturaleza"],
  },
  {
    label: "Sociedad",
    genres: ["Historia", "Biografía", "Política", "Derecho", "Educación", "Negocios", "Religión"],
  },
  {
    label: "Arte y cultura",
    genres: ["Arte", "Música", "Cocina", "Viajes", "Deportes"],
  },
  {
    label: "Infantil y juvenil",
    genres: ["Infantil", "Juvenil"],
  },
];
